############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# Welcome to the cState configuration file!
#
# If you are using an earlier version, or one
# in the future, such as v8.0 you may see errors
# pop up when deploying a cState website.
#
# Now, onto the fun part.
#
# Hugo is used for building the status page,
# so this file can be used to change how
# your status page should behave or look.
#
# If you want to use special characters,
# such as accented letters, you MUST save
# the file as UTF-8, not ANSI.
#
# If cState does not load, ensure that:
#  - No tabs are present;
#    YAML only allows spaces
#  - Indents are correct
#    YAML hierarchy is based entirely on indentation
#  - You have "escaped" all apostrophes
#    in your text: If you want to write "don't",
#    for example, write "don''t" instead!
#    Note the doubled apostrophe.
#  - Text with symbols is enclosed in single
#    or double quotation marks.
#
# If you have problems, create an issue on GitHub:
# https://github.com/cstate/cstate/issues

############################################################
# +------------------------------------------------------+ #
# |                  Basic metadata                      | #
# +------------------------------------------------------+ #
############################################################

title: AlmaLinux Status
buildFuture: true
languageCode: en
defaultContentLanguage: en
baseURL: https://status.almalinux.org
enableGitInfo: true

############################################################
# +------------------------------------------------------+ #
# |                   Preferences                        | #
# +------------------------------------------------------+ #
############################################################

params:
  categories:
    - name: AlmaLinux Services
      closed: false

  systems:
    - name: Accounts (accounts.almalinux.org)
      category: AlmaLinux Services
    - name: AlmaLinux Build System (build.almalinux.org)
      category: AlmaLinux Services
    - name: Bugs (bugs.almalinux.org)
      category: AlmaLinux Services
    - name: Mailing Lists (lists.almalinux.org)
      category: AlmaLinux Services
    - name: Repositories (repo.almalinux.org)
      category: AlmaLinux Services
    - name: Gitea (git.almalinux.org)
      category: AlmaLinux Services
    - name: Forums (forums.almalinux.org)
      category: AlmaLinux Services
    - name: Mattermost (chat.almalinux.org)
      category: AlmaLinux Services
    - name: Errata (errata.almalinux.org)
      category: AlmaLinux Services
    - name: Mirror Service - Primary Mirrors
      category: AlmaLinux Services
    - name: Mirror Service - Secondary Mirrors
      category: AlmaLinux Services
    - name: Website (www.almalinux.org)
      category: AlmaLinux Services
    - name: Wiki (wiki.almalinux.org)
      category: AlmaLinux Services
    - name: Paste (paste.almalinux.org)
      category: AlmaLinux Services
    - name: Shop (shop.almalinux.org)
      category: AlmaLinux Services
    - name: OpenProject (openproject.almalinux.org)
      category: AlmaLinux Services

  dateFormat: January 2, 2006 at 3:04 PM UTC
  shortDateFormat: 15:04 UTC — Jan 2
  useRelativeTime: true
  skipSeconds: false
  enableLastMod: true
  useLargeHeaderDesign: false
  incidentHistoryFormat: "yearly"
  enableCustomHTML: true
  disableIncidentHistory: false
  disableDarkMode: false
  useLogo: true
  logo: logo.svg
  description: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here.
  disableComplexCalculations: false
  incidentPostsPerPage: 10
  brand: "#0a0c0f"
  ok: "#44790c"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"
  alwaysKeepBrandColor: true
  headerTextColor: white
  googleAnalytics: UA-00000000-1

theme: cstate
preserveTaxonomyNames: true

taxonomies:
  affected: affected

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg

outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml

